# Generated by Django 4.2.7 on 2023-11-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ads_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
